### ISSUE TITLE
fit_generator

### ISSUE THREAD

**Issue by phobrain** [kutoga/going_deeper#3]
Newbie asked/answered: Instead of model.fit_generator() I'm using 

    from multiprocessing import Process, Queue

    train_q = Queue(2)
    test_q = Queue(2)

    def myGen(tag, q, pairs, labels, batch_size, shuffle):
        while True:
            #in place of yield:
             q.put((t, tt))

    train_gen = Process(
        target=myGen,
        args=('data', train_q, tr_data, tr_y, batch_size, True)
    )
    train_gen.start()

    for i in range(epochs): # as in loop in mnist demo

        x_train, y_train = train_q.get()
        res = model.train_batch(x_train, y_train, ...)

Will close when I get it all working.

**Comment by kutoga** [comment]
I have to have a more detailed look at this issue; this probably takes some days, because currently my time is very limited. I'm sorry.

But currently, I don't see the problem with the code: You just want to generate the data in an external process and use it for the training? Doesn't your code work? What error do you get?

**Comment by phobrain** [comment]
The code above did what I was trying to figure out.

Closing for now, reexamine in 100 years.
