### ISSUE TITLE
Input being fed to >1 Dense? 'dense_6' getting input dim instead of dense_size

### ISSUE THREAD

**Issue by phobrain** [kutoga/going_deeper#4]
Pre question: is 'trainable=False' necessary for plain Dense? I couldn't find what it does; doesn't affect this issue. .. I vote for 'GInfLayer()' as easier to subvocalize, btw.

input_shape: (2980,)
dense_size: 175

    model = TDModel()
    model += Input(input_shape)
    model += GInftlyLayer(
                     .. Dense(dense_size), Dropout(0.1), GammaEtc .. Activation('relu') ...
    )
    model += Dense(dense_size/4)
    model += GInftlyLayer(
                     .. Dense(dense_size), Dropout(0.1), GammaEtc .. Activation('relu') ...
    )
    model.init(
       optimizer='adadelta',
       loss='categorical_crossentropy',
       metrics=['categorical_accuracy']
     )

dense_6: expected axis -1 of input shape to have value 175 but got shape (None, 2980)

Rebuild model...
Rebuild model...
Traceback (most recent call last):
  File "asym.py", line 499, in create_network
    metrics=['categorical_accuracy']
  File "/hdd/phobrain/keras/hp2/ginfty.py", line 360, in init
    self.rebuild_model_if_required()
  File "/hdd/phobrain/keras/hp2/ginfty.py", line 319, in rebuild_model_if_required
    nw = layer(nw)
  File "/home/phobrain/anaconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 586, in __call__
    self.assert_input_compatibility(inputs)
  File "/home/phobrain/anaconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 496, in assert_input_compatibility
    ' but got shape ' + str(x_shape))
ValueError: Input 0 is incompatible with layer dense_6: expected axis -1 of input shape to have value 175 but got shape (None, 2980)

**Comment by kutoga** [comment]
The problem is that the `GInftyLayer`-layer requires that the input shape before the layer is equal to the output shape of the layer.

Therefore, before the layer, the shape must already be correct. The reason fir this might be seen on page 5 on Figure 3 of the following document:
https://github.com/kutoga/going_deeper/blob/master/doc/going_deeper.pdf

Basically the input is always added to the processed result: This element-wise addition requires that the two given tensors (the input to `GInftyLayer` and the output of fi(x)) have the same shape.

To handle this, I used non-trainable layers in the experiments to reshape the data:
https://github.com/kutoga/going_deeper/blob/master/experiment_00_xor.py#L28
https://github.com/kutoga/going_deeper/blob/master/experiment_01_mnist.py#L42
https://github.com/kutoga/going_deeper/blob/master/experiment_01_mnist.py#L58
https://github.com/kutoga/going_deeper/blob/master/experiment_01_mnist.py#L75

The concept implies this. I do not see a nice solution to change this, but with the correct input shape it works. In your example, you could use a trainable layer to reshape the data or an untrainable layer.

Solution with a trainable layer:

```
model = TDModel()
model += Input(input_shape)
**model += Dense(dense_size)**
model += GInftlyLayer(
                 .. Dense(dense_size), Dropout(0.1), GammaEtc .. Activation('relu') ...
)
model += Dense(dense_size/4)
**model += Dense(dense_size)**
model += GInftlyLayer(
                 .. Dense(dense_size), Dropout(0.1), GammaEtc .. Activation('relu') ...
)
model.init(
   optimizer='adadelta',
   loss='categorical_crossentropy',
   metrics=['categorical_accuracy']
 )
```
The solution with a layer that contains random and fixed weights:

```
model = TDModel()
model += Input(input_shape)
**model += Dense(dense_size, trainable=False)**
model += GInftlyLayer(
                 .. Dense(dense_size), Dropout(0.1), GammaEtc .. Activation('relu') ...
)
model += Dense(dense_size/4)
**model += Dense(dense_size, trainable=False)**
model += GInftlyLayer(
                 .. Dense(dense_size), Dropout(0.1), GammaEtc .. Activation('relu') ...
)
model.init(
   optimizer='adadelta',
   loss='categorical_crossentropy',
   metrics=['categorical_accuracy']
 )
```

Probably the solution with the trainable weights works better in practice. I only used the fixed weights to show that the `GInftyLayer`-layer is the layer that learns something and not the layer before or after.

**Comment by phobrain** [comment]
Thanks! On to next..
